apiVersion: v1
appVersion: "latest"
description: A Matrix-Hangouts puppeting bridge
name: mautrix-hangouts
version: 0.1.1
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - hangouts
home: https://matrix.org/docs/projects/bridge/mautrix-hangouts/
sources:
  - https://github.com/tulir/mautrix-hangouts
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
