apiVersion: v2
type: application
appVersion: v0.3.3
version: 1.0.3
name: mautrix-googlechat
description: A Matrix-Hangouts puppeting bridge (Now externally called mautrix-googlechat)
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - hangouts
  - googlechat
home: https://github.com/mautrix/googlechat
sources:
  - https://github.com/mautrix/googlechat
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - fix: update values to match the actual defaults now: ([82b6cda813935097cafd2bdfe8801e8bc0f4de13](https://github.com/halkeye-helm-charts/mautrix-googlechat/commit/82b6cda813935097cafd2bdfe8801e8bc0f4de13))
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: mautrix-googlechat
      image: "dock.mau.dev/mautrix/googlechat:v0.3.3"
