{{- if .Values.config }}
{{- if .Values.config.appservice }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-hangouts.fullname" . }}
  labels:
{{ include "mautrix-hangouts.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "need config.appservice.port" .Values.config.appservice.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mautrix-hangouts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
